const products = [
  { id: 1, name: "Blusa Drapeado Sereno", category: "Blusa", price: 129, originalPrice: 199.90, badge: "SALE",
    image: "assets/p-blusa-azul.png",
    colors: [{ name: "Azul Sereno", hex: "#9CAEB8" }],
    sizes: ["36","42"],
    description: "Blusa de tecido fluido com drapeado assimétrico que valoriza o corpo com suavidade. Ideal para compor looks do dia a dia com elegância descomplicada.",
    material: "96% viscose, 4% elastano. Tecido leve, fluido e de toque macio. Não amassa.",
    care: "Lavar à mão ou na máquina em ciclo delicado, água fria. Não torcer. Secar à sombra na horizontal.",
    fit: "Modelagem solta com queda suave. Veste bem nos tamanhos 34 ao 42. A modelo usa tamanho 36."
  },
  { id: 2, name: "Vestido Citrus", category: "Vestido Midi", price: 149, originalPrice: null, badge: "NOVO",
    image: "assets/p-vestido-laranja.png",
    colors: [{ name: "Laranja Citrus", hex: "#F4A05B" }, { name: "Rosa Claro", hex: "#F4C9D8" }],
    sizes: ["P","M","G"],
    description: "Vestido midi vibrante em tom citrus, com caimento elegante e corte que valoriza a silhueta. Uma peça que transforma qualquer dia em celebração.",
    material: "100% algodão com fio egípcio. Tecido respirável, macio e de alta durabilidade.",
    care: "Lavar na máquina em ciclo delicado com água fria. Passar com ferro morno pelo avesso.",
    fit: "Modelagem ajustada no busto com saia evazê. Para um caimento soltinho, suba um tamanho."
  },
  { id: 3, name: "Conjunto Rosé", category: "Conjunto Cropped", price: 259, originalPrice: null, badge: "NOVO",
    image: "assets/p-conjunto-rosa.png",
    colors: [{ name: "Rosé", hex: "#E29AB0" }, { name: "Nude", hex: "#F9EFF0" }],
    sizes: ["36","38","40","42"],
    description: "Conjunto cropped + calça pantalona em tecido de malha rosé. Peças vendidas juntas que combinam conforto e sofisticação em harmonia perfeita.",
    material: "85% poliéster, 15% elastano. Malha de alta compressão com brilho acetinado.",
    care: "Lavar à mão com sabão neutro. Não usar amaciante. Secar à sombra.",
    fit: "Cropped com ajuste abaixo do busto. Calça modelagem slim de cintura alta. Segue tabela padrão."
  },
  { id: 4, name: "Body Bronze", category: "Body Drapeado", price: 199, originalPrice: null, badge: "EXCLUSIVO",
    image: "assets/p-body-marrom.png",
    colors: [{ name: "Bronze Escuro", hex: "#7A4234" }, { name: "Caramelo", hex: "#C4956A" }],
    sizes: ["P"],
    description: "Body drapeado em tom bronze com abertura profunda nas costas. Peça exclusiva que exige atitude, para noites que ficam na memória.",
    material: "78% nylon, 22% elastano. Tecido com compressão suave e acabamento fosco premium.",
    care: "Lavar somente à mão com água fria e sabonete neutro. Secar sobre superfície plana.",
    fit: "Modelagem colada ao corpo. Recomendamos medir busto e quadril antes de escolher. Disponível em tamanho P."
  },
  { id: 5, name: "Saia Cetim Lua", category: "Saia Longa", price: 239, originalPrice: null, badge: null,
    image: "assets/p-saia-cetim.png",
    colors: [{ name: "Prata Lua", hex: "#C9CACE" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["36","38","40"],
    description: "Saia longa de cetim com reflexos suaves que evocam o brilho da lua. Fluida, elegante e atemporal, a peça-chave de um guarda-roupa consciente.",
    material: "100% poliéster cetinado de gramatura alta. Forro interno em chiffon.",
    care: "Lavar na máquina em ciclo delicado. Passar com ferro a vapor pelo avesso em temperatura média.",
    fit: "Cós elástico para conforto máximo. Comprimento midi até o tornozelo (aprox. 90cm). Para corpos mais altos, considere um tamanho acima."
  },
  { id: 6, name: "Blazer Camélia", category: "Blazer", price: 379, originalPrice: null, badge: "NOVO",
    image: "assets/p-blazer-caqui.png",
    colors: [{ name: "Caqui Camélia", hex: "#8C7350" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["38","40","42"],
    description: "Blazer estruturado em tweed misto com botões dourados e lapela clássica. Transita do trabalho à noite com elegância natural e sem esforço.",
    material: "60% lã, 35% poliéster, 5% elastano. Forro de seda sintética. Botões em metal dourado.",
    care: "Limpeza a seco recomendada. Para lavagem em casa, ciclo delicado em água fria com cuidado extra na estrutura dos ombros.",
    fit: "Modelagem slim com ombros levemente estruturados. Caimento alinhado ao corpo. Comprimento no quadril."
  },
  { id: 7, name: "Regata Pérola", category: "Regata Cetim", price: 89, originalPrice: 139.90, badge: "SALE",
    image: "assets/p-regata-branca.png",
    colors: [{ name: "Pérola", hex: "#F5F2EC" }, { name: "Bege", hex: "#E8DDD0" }],
    sizes: ["P","M","G","GG"],
    description: "Regata de cetim leve com alças finas e bojo removível. Uma peça versátil que funciona sozinha ou por baixo de sobreposições com charme discreto.",
    material: "100% seda sintética cetinada. Bojo em esponja removível. Alças reguláveis.",
    care: "Lavar somente à mão com sabonete neutro. Não torcer. Secar à sombra deitada sobre toalha.",
    fit: "Modelagem ajustada com bojo leve. Para usar por baixo de blazers e sobreposições, suba um tamanho."
  },
  { id: 8, name: "Conjunto Cargo Azul", category: "conjuntos", price: 199.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-cargo-azul.png",
    colors: [{ name: "Azul Claro", hex: "#8FA8C0" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    description: "Conjunto urbano com calça cargo azul de cintura alta e body preto gola alta. Combinação arrojada que une estilo despojado e feminilidade com muita personalidade.",
    material: "Calça em gabardine leve com bolsos laterais. Body em malha elástica confortável.",
    care: "Lavar na máquina em ciclo delicado, água fria. Não usar secadora.",
    fit: "Calça de cintura alta modelagem ampla. Body ajustado ao corpo. Segue tabela padrão."
  },
  { id: 9, name: "Conjunto Linho Bege", category: "conjuntos", price: 179.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-conj-bege.png",
    colors: [{ name: "Bege Off-White", hex: "#E8DDD0" }],
    sizes: ["P","M","G","GG"],
    description: "Conjunto elegante em linho bege com short de cintura alta e blusa estruturada. Perfeito para almoços e eventos ao ar livre com toda a sofisticação que você merece.",
    material: "70% linho, 30% viscose. Tecido respirável e de toque suave.",
    care: "Lavar na máquina em ciclo delicado, água fria. Passar com ferro morno.",
    fit: "Short de cintura alta com cós largo. Blusa com modelagem reta e levemente ampla."
  },
  { id: 10, name: "Macacão Glamour Nude", category: "conjuntos", price: 239.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-macacao-nude.png",
    colors: [{ name: "Nude", hex: "#C4956A" }, { name: "Bege", hex: "#E8DDD0" }],
    sizes: ["P","M","G"],
    description: "Macacão curto em tom nude com cinto dourado que valoriza a silhueta. Peça versátil que passa do trabalho à balada com elegância e praticidade únicos.",
    material: "95% poliéster, 5% elastano. Tecido com leve brilho acetinado.",
    care: "Lavar à mão com sabão neutro em água fria. Não usar secadora.",
    fit: "Modelagem ajustada com decote em V. Cinto removível. Segue tabela padrão."
  },
  { id: 11, name: "Conjunto Preto Refinado", category: "conjuntos", price: 199.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-conj-preto.png",
    colors: [{ name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G","GG"],
    description: "Conjunto preto atemporal com short de alfaiataria e blusa sem mangas estruturada. O cinto dourado completa o look com sofisticação que nunca sai de moda.",
    material: "Crepe de alta qualidade com caimento impecável. Cinto em metal dourado incluso.",
    care: "Lavar na máquina ciclo delicado, separado das roupas coloridas.",
    fit: "Short de cintura alta com abertura lateral. Blusa com alças largas. Segue tabela padrão."
  },
  { id: 12, name: "Tricot Rosê Manguinha", category: "blusas", price: 159.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-tricot-rose.png",
    colors: [{ name: "Rosê", hex: "#C4826A" }, { name: "Caramelo", hex: "#C4956A" }],
    sizes: ["P","M","G"],
    description: "Blusa tricot rosê one-shoulder com manga fina e textura canelada. Combina elegância casual com o conforto do tricot para um visual sofisticado no dia a dia.",
    material: "80% viscose, 20% poliamida. Tricot canelado de malha fina.",
    care: "Lavar à mão com água fria e sabonete neutro. Secar à sombra deitado.",
    fit: "Modelagem ajustada. One-shoulder com alça única. Recomendamos verificar a tabela de medidas."
  },
  { id: 13, name: "Tricot Marrom Gola Alta", category: "blusas", price: 189.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-tricot-marrom.png",
    colors: [{ name: "Marrom Chocolate", hex: "#4A2F1A" }, { name: "Caramelo", hex: "#C4956A" }],
    sizes: ["P","M","G","GG"],
    description: "Tricot de gola alta em marrom chocolate com textura torcida que aquece com estilo. Uma peça de inverno que não abre mão da elegância em nenhum momento.",
    material: "60% lã merino, 40% acrílico. Tricot de espessura média com toque suave.",
    care: "Lavar à mão com sabão especial para lã em água fria. Secar deitado à sombra.",
    fit: "Modelagem solta e confortável. Gola alta que pode ser dobrada. Manga longa."
  },
  { id: 14, name: "Look Tricot Cinza + Short Saia", category: "conjuntos", price: 189.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-look-cinza.png",
    colors: [{ name: "Cinza", hex: "#9A9A9A" }, { name: "Marrom", hex: "#6B4226" }],
    sizes: ["P","M","G"],
    description: "Look poderoso com tricot cropped cinza e short saia de couro marrom. Contraste de texturas que cria um visual editorial cheio de atitude e feminilidade.",
    material: "Tricot em viscose canelada. Short saia em couro ecológico de alta qualidade.",
    care: "Tricot: lavar à mão. Short saia: limpar com pano úmido.",
    fit: "Tricot cropped com barra assimétrica. Short saia de cintura alta com botões laterais."
  },
  { id: 15, name: "Look Tricot Azul + Calça Couro", category: "conjuntos", price: 189.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-look-azul.png",
    colors: [{ name: "Azul Marinho", hex: "#1A2744" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    description: "Combinação sofisticada de tricot azul marinho com calça de couro preta. Look poderoso para ocasiões especiais que pede confiança e estilo.",
    material: "Tricot em viscose grossa. Calça em couro ecológico com elastano.",
    care: "Tricot: lavar à mão com água fria. Calça: limpar com pano úmido e condicionador de couro.",
    fit: "Tricot cropped one-shoulder. Calça slim de cintura alta com fechamento lateral."
  },
  { id: 16, name: "Macacão Estampa Zebra", category: "conjuntos", price: 299.90, originalPrice: null, badge: "EXCLUSIVO",
    image: "assets/lj-macacao-zebra.png",
    colors: [{ name: "Animal Print", hex: "#F5F0E8" }],
    sizes: ["P","M","G"],
    description: "Macacão pantalona em estampa zebra com ombro único e lenço coordenado. Uma declaração de moda para quem não tem medo de ser notada e adora tendências.",
    material: "100% viscose com estampa animal print exclusiva. Tecido leve e fluido.",
    care: "Lavar à mão ou em ciclo delicado. Não usar alvejante.",
    fit: "Modelagem ampla pantalona. Ombro único com lenço decorativo incluso. Cinto incluso."
  },
  { id: 17, name: "Conjunto Off-White Drapeado", category: "conjuntos", price: 229.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-conj-offwhite.png",
    colors: [{ name: "Off-White", hex: "#F5F0E8" }, { name: "Bege", hex: "#E8DDD0" }],
    sizes: ["P","M","G"],
    description: "Conjunto refinado com top drapeado assimétrico e short saia off-white. A combinação perfeita de elegância e leveza para eventos e jantares sofisticados.",
    material: "95% poliéster, 5% elastano. Tecido drapeado de alta fluidez com leve brilho.",
    care: "Lavar à mão com sabão neutro em água fria. Secar à sombra.",
    fit: "Top com drapeado frontal e amarração nas costas. Short saia com cós elástico."
  },
  { id: 18, name: "Corset Preto", category: "blusas", price: 129.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-corset-preto.png",
    colors: [{ name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    description: "Corset preto estruturado que define a silhueta com elegância. Versátil para usar por dentro da calça ou saia, transforma qualquer look em um statement de moda.",
    material: "Tecido estruturado com barbatanas internas e forro. Fechamento frontal com colchetes.",
    care: "Lavar somente à mão com cuidado nas barbatanas. Não torcer.",
    fit: "Corset com modelagem estruturada. Consulte tabela de medidas de busto para escolher o tamanho."
  },
  { id: 19, name: "Vestido Verde Longo Renda", category: "vestidos", price: 299.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-vestido-verde.png",
    colors: [{ name: "Verde Esmeralda", hex: "#2E7D4F" }],
    sizes: ["P","M","G"],
    description: "Vestido longo verde esmeralda com renda bordada e recorte lateral. Uma peça deslumbrante para ocasiões especiais que pede toda a atenção para você.",
    material: "Tecido principal em crepe. Renda em 100% poliéster com bordado artesanal.",
    care: "Limpeza a seco recomendada. Lavar à mão com muito cuidado na renda.",
    fit: "Modelagem ajustada no busto e quadril com saia fluida. Recorte lateral com elástico."
  },
  { id: 20, name: "Vestido Preto Paetê", category: "vestidos", price: 249.90, originalPrice: null, badge: "EXCLUSIVO",
    image: "assets/lj-vestido-paete.png",
    colors: [{ name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    description: "Vestido curto preto com saia em paetê brilhante e top recortado. A pedida certeira para noites inesquecíveis que merecem uma peça à altura da ocasião.",
    material: "Top em tecido elástico. Saia em tecido de paetê costurado à mão.",
    care: "Limpeza a seco recomendada para preservar o paetê.",
    fit: "Top ajustado com recorte frontal. Saia rodada acima do joelho. Modelagem estruturada."
  },
  { id: 21, name: "Colete Vermelho", category: "blazers", price: 99.90, originalPrice: null, badge: "NOVO",
    image: "assets/lj-colete-vermelho.png",
    colors: [{ name: "Vermelho", hex: "#C0392B" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G","GG"],
    description: "Colete vermelho com botões dourados para compor looks poderosos. Peça coringa que transforma qualquer produção em um visual elegante e marcante.",
    material: "Crepe de alta qualidade com forro interno. Botões em metal dourado.",
    care: "Lavar na máquina em ciclo delicado ou limpeza a seco para maior durabilidade.",
    fit: "Modelagem ajustada com botões na frente. Sem mangas. Comprimento na cintura."
  },
  { id: 22, name: "Macacão Branco One-Shoulder", category: "conjuntos", price: 389.90, originalPrice: null, badge: "EXCLUSIVO",
    image: "assets/lj-macacao-branco.png",
    colors: [{ name: "Branco", hex: "#FAFAFA" }, { name: "Off-White", hex: "#F5F0E8" }],
    sizes: ["38","40","42"],
    description: "Macacão pantalona branco one-shoulder com drapeado sofisticado. Uma peça de luxo para eventos formais, casamentos e festas que exigem elegância impecável.",
    material: "100% viscose premium com leve elastano. Acabamento de alta costura.",
    care: "Limpeza a seco recomendada. Lavar à mão somente em água fria com sabão neutro.",
    fit: "Modelagem pantalona de cintura alta. Ombro único estruturado. Disponível nos números 38, 40 e 42."
  },
  { id: 23, name: "Cropped Couro Caramelo", category: "blusas", price: 189.00, originalPrice: null, badge: "NOVO",
    image: "assets/lj-cropped-caramelo.png",
    colors: [{ name: "Caramelo", hex: "#C4956A" }, { name: "Preto", hex: "#1C1414" }],
    sizes: ["P","G"],
    description: "Cropped em couro ecológico caramelo com bojo embutido e barra reta. Peça versátil que eleva qualquer look com um toque de atitude e feminilidade sofisticada.",
    material: "Couro ecológico de alta qualidade com forro interno e bojo removível.",
    care: "Limpar com pano úmido suave. Não mergulhar em água. Aplicar condicionador de couro periodicamente.",
    fit: "Modelagem ajustada com bojo embutido. Disponível em P e G. Consulte tabela de medidas."
  },
  { id: 24, name: "Short Couro Preto", category: "calcas", price: 69.90, originalPrice: 99.90, badge: "SALE",
    image: "assets/lj-short-couro.png",
    colors: [{ name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    description: "Short de couro ecológico preto com cinto de argolas e cintura alta. Uma peça statement que combina rock e feminilidade para looks ousados e cheios de estilo.",
    material: "Couro ecológico com forro interno. Cinto de argolas removível incluso.",
    care: "Limpar com pano úmido. Não lavar na máquina. Guardar em local arejado.",
    fit: "Cintura alta com cós largo. Modelagem reta. Disponível em P, M e G."
  },
  { id: 25, name: "Calça Jeans Reta", category: "calcas", price: 279.00, originalPrice: null, badge: "NOVO",
    image: "assets/lj-calca-jeans.png",
    colors: [{ name: "Azul Médio", hex: "#4A6FA5" }, { name: "Azul Escuro", hex: "#2C3E6B" }],
    sizes: ["38","40","42"],
    description: "Calça jeans reta de cintura alta com caimento impecável e tecido premium. Uma peça essencial no guarda-roupa feminino que combina com absolutamente tudo.",
    material: "98% algodão, 2% elastano. Jeans premium lavagem média com tratamento antidesbotamento.",
    care: "Lavar na máquina ao contrário em água fria. Não usar alvejante. Secar à sombra.",
    fit: "Modelagem reta de cintura alta. Disponível nos números 38, 40 e 42."
  },
  { id: 26, name: "Vestido Vermelho Midi", category: "vestidos", price: 189.00, originalPrice: 299.00, badge: "SALE",
    image: "assets/lj-vestido-vermelho.png",
    colors: [{ name: "Vermelho", hex: "#C0392B" }],
    sizes: ["P","GG"],
    description: "Vestido midi vermelho com franzido lateral que valoriza cada curva com elegância. Para ocasiões especiais onde você quer ser a protagonista da noite.",
    material: "95% poliéster, 5% elastano. Tecido de malha stretch com franzido.",
    care: "Lavar na máquina em ciclo delicado. Não torcer. Pendurar para secar.",
    fit: "Modelagem ajustada com franzido no quadril. Disponível em P e GG. Comprimento midi."
  },
  { id: 27, name: "Regata Tule Preta", category: "blusas", price: 89.00, originalPrice: 139.90, badge: "SALE",
    image: "assets/lj-regata-preta.png",
    colors: [{ name: "Preto", hex: "#1C1414" }, { name: "Branco", hex: "#FAFAFA" }],
    sizes: ["38","40","42"],
    description: "Regata preta com sobreposição em tule transparente e alças estruturadas. Peça sofisticada que transita entre o dia e a noite com charme e elegância incomparáveis.",
    material: "Regata em cetim. Sobreposto em tule 100% poliéster. Alças reguláveis.",
    care: "Lavar à mão com sabonete neutro em água fria. Secar à sombra deitada.",
    fit: "Modelagem ajustada. Alças reguláveis. Disponível nos números 38, 40 e 42."
  },
  { id: 28, name: "Cropped Floral Rosa", category: "blusas", price: 79.00, originalPrice: 129.90, badge: "SALE",
    image: "assets/lj-cropped-floral.png",
    colors: [{ name: "Rosa Floral", hex: "#E8708A" }, { name: "Branco", hex: "#FAFAFA" }],
    sizes: ["P","M","G"],
    description: "Cropped com estampa floral vibrante em rosa e branco. Peça alegre e cheia de personalidade perfeita para dias ensolarados e looks despojados e femininos.",
    material: "100% viscose com estampa digital exclusiva. Tecido leve e fresco.",
    care: "Lavar na máquina em ciclo delicado, separado de roupas escuras. Secar à sombra.",
    fit: "Cropped com barra reta. Decote na frente. Modelagem ajustada. Segue tabela padrão."
  },
  { id: 29, name: "Body One-Shoulder Nude", category: "blusas", price: 199.00, originalPrice: null, badge: "NOVO",
    image: "assets/lj-body-nude.png",
    colors: [{ name: "Nude", hex: "#D4A882" }, { name: "Marrom", hex: "#7A4234" }],
    sizes: ["P","M","G"],
    description: "Body one-shoulder nude com drapeado suave no decote e tecido de segunda pele. Uma peça elegante e sensual que combina com qualquer saia ou calça.",
    material: "92% poliamida, 8% elastano. Tecido de alta compressão com efeito segunda pele.",
    care: "Lavar somente à mão com água fria e sabonete neutro. Secar sobre superfície plana.",
    fit: "Modelagem ajustada ao corpo. One-shoulder com alça única. Fecho com colchetes na entreperna."
  },
  { id: 30, name: "Blazer Xadrez", category: "blazers", price: 349.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-blazer-xadrez-1.jpg",
    images: ["assets/nrl-blazer-xadrez-1.jpg","assets/nrl-blazer-xadrez-2.jpg","assets/nrl-blazer-xadrez-3.jpg","assets/nrl-blazer-xadrez-4.jpg"],
    video: "assets/nrl-blazer-xadrez.mp4",
    colors: [{ name: "Xadrez Clássico", hex: "#4A4040" }],
    sizes: ["P","M","G"],
    description: "Blazer xadrez estruturado com caimento impecável e estampa clássica que nunca sai de moda. Peça versátil que transita do casual ao formal com atitude e elegância.",
    material: "Tecido xadrez de alta qualidade com forro interno. Estrutura de ombro levemente marcada.",
    care: "Limpeza a seco recomendada. Para lavagem doméstica, ciclo delicado em água fria.",
    fit: "Modelagem slim com ombros estruturados. Comprimento no quadril. Segue tabela padrão."
  },
  { id: 31, name: "Blusa Tule Floral", category: "blusas", price: 119.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-blusa-tule.jpg",
    colors: [{ name: "Natural", hex: "#F5EFE6" }],
    sizes: ["P","M","G"],
    description: "Blusa em tule delicado com bordado floral artesanal que traz leveza e romantismo a qualquer look. Uma peça que celebra a feminilidade com suavidade e charme.",
    material: "100% poliéster em tule de alta gramatura. Bordado artesanal aplicado à mão.",
    care: "Lavar somente à mão com sabão neutro em água fria. Secar à sombra estendida.",
    fit: "Modelagem ampla e fluida. Manga longa ou 3/4. Veste folgado, considere um tamanho abaixo se preferir mais ajustado."
  },
  { id: 32, name: "Conjunto Crochê", category: "conjuntos", price: 319.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-colete-croche.jpg",
    images: ["assets/nrl-colete-croche.jpg","assets/nrl-calca-croche.jpg"],
    colors: [{ name: "Natural", hex: "#D4C5A9" }],
    sizes: ["P","M","G"],
    pieceOptions: [
      { name: "Conjunto Completo", price: 319.00 },
      { name: "Somente Colete", price: 179.00 },
      { name: "Somente Calça", price: 189.00 }
    ],
    description: "Conjunto em crochê artesanal com colete e calça de cintura alta. Peças que podem ser adquiridas juntas ou separadamente para combinar com o restante do seu guarda-roupa.",
    material: "Crochê artesanal em fio de algodão 100% natural. Cada peça é única com pequenas variações do processo manual.",
    care: "Lavar à mão com sabão neutro em água fria. Secar à sombra deitado sobre toalha. Não torcer.",
    fit: "Colete com modelagem cropped. Calça de cintura alta com caimento fluido. Ambas seguem tabela padrão."
  },
  { id: 33, name: "Conjunto Jeans", category: "conjuntos", price: 259.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-conjunto-jeans-1.jpg",
    images: ["assets/nrl-conjunto-jeans-1.jpg"],
    colors: [{ name: "Azul Médio", hex: "#4A6FA5" }],
    sizes: ["P","M","G"],
    pieceOptions: [
      { name: "Conjunto Completo", price: 259.00 },
      { name: "Somente Top", price: 119.00 },
      { name: "Somente Calça Jeans", price: 179.00 }
    ],
    description: "Conjunto jeans sofisticado com top e calça de cintura alta. Podem ser adquiridos juntos ou separadamente para criar combinações únicas no seu estilo.",
    material: "98% algodão, 2% elastano. Denim de alta qualidade com lavagem cuidadosa.",
    care: "Lavar ao contrário em ciclo delicado, água fria. Não usar alvejante. Secar à sombra.",
    fit: "Top ajustado com barra reta. Calça reta de cintura alta. Segue tabela padrão de tamanhos."
  },
  { id: 34, name: "Conjunto Tweed", category: "conjuntos", price: 329.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-conjunto-tweed-1.jpg",
    images: ["assets/nrl-conjunto-tweed-1.jpg","assets/nrl-conjunto-tweed-2.jpg"],
    colors: [{ name: "Tweed Multicolor", hex: "#8C7E6A" }],
    sizes: ["P","M","G"],
    pieceOptions: [
      { name: "Conjunto Completo", price: 329.00 },
      { name: "Somente Blazer", price: 199.00 },
      { name: "Somente Saia", price: 169.00 }
    ],
    description: "Conjunto tweed elegante com blazer estruturado e saia midi. As peças se complementam com perfeição mas também brilham separadas em diferentes composições.",
    material: "Tweed misto com fio de lã e poliéster. Forro interno nas duas peças. Botões refinados.",
    care: "Limpeza a seco recomendada. Guardar em cabide para manter a estrutura.",
    fit: "Blazer modelagem slim com ombros marcados. Saia midi de cintura alta com forro interno."
  },
  { id: 35, name: "Conjunto Corset + Short", category: "conjuntos", price: 229.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-corset-short.jpg",
    images: ["assets/nrl-corset-short.jpg"],
    colors: [{ name: "Preto", hex: "#1C1414" }],
    sizes: ["P","M","G"],
    pieceOptions: [
      { name: "Conjunto Completo", price: 229.00 },
      { name: "Somente Corset", price: 149.00 },
      { name: "Somente Short", price: 99.00 }
    ],
    description: "Conjunto corset estruturado com short de cintura alta. Combinação ousada e sofisticada que define a silhueta com atitude. Cada peça funciona perfeitamente sozinha.",
    material: "Corset em tecido estruturado com barbatanas e forro. Short em tecido de alta qualidade com cós largo.",
    care: "Lavar somente à mão com cuidado. Não torcer o corset para preservar a estrutura.",
    fit: "Corset com modelagem estruturada que define a cintura. Short de cintura alta modelagem reta. Consulte tabela de medidas."
  },
  { id: 36, name: "Macacão Listrado", category: "conjuntos", price: 279.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-macacao-listrado-1.jpg",
    images: ["assets/nrl-macacao-listrado-1.jpg","assets/nrl-macacao-listrado-2.jpg","assets/nrl-macacao-listrado-3.jpg"],
    colors: [{ name: "Listrado P&B", hex: "#2C2C2C" }],
    sizes: ["P","M","G"],
    description: "Macacão listrado com caimento elegante e design moderno. As listras verticais alongam a silhueta e a modelagem fluida garante conforto e sofisticação em cada movimento.",
    material: "Viscose premium com elastano. Listras tecidas no próprio fio para maior durabilidade da estampa.",
    care: "Lavar na máquina em ciclo delicado, água fria. Não usar secadora. Secar à sombra.",
    fit: "Modelagem fluida e levemente ampla. Cós marcado. Para um caimento mais justo, suba um tamanho abaixo."
  },
  { id: 37, name: "Vestido Onça", category: "vestidos", price: 259.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-vestido-onca-1.jpg",
    images: ["assets/nrl-vestido-onca-1.jpg","assets/nrl-vestido-onca-2.jpg"],
    colors: [{ name: "Animal Print Onça", hex: "#C4956A" }],
    sizes: ["P","M","G"],
    description: "Vestido com estampa animal print onça que é sinônimo de poder e ousadia. Caimento impecável que valoriza a silhueta para quem não tem medo de ser notada.",
    material: "Tecido de alta qualidade com estampa digital exclusiva. Leve elastano para conforto.",
    care: "Lavar em ciclo delicado, água fria. Separar de roupas claras. Secar à sombra.",
    fit: "Modelagem ajustada com caimento que valoriza as curvas. Comprimento midi. Segue tabela padrão."
  },
  { id: 38, name: "Vestido Vinho", category: "vestidos", price: 229.00, originalPrice: null, badge: "NOVO",
    image: "assets/nrl-vestido-vinho-1.jpg",
    images: ["assets/nrl-vestido-vinho-1.jpg","assets/nrl-vestido-vinho-2.jpg"],
    colors: [{ name: "Vinho", hex: "#722F37" }],
    sizes: ["P","M","G"],
    description: "Vestido vinho com design sofisticado que combina elegância e feminilidade. A cor profunda e o caimento impecável fazem desta peça a escolha perfeita para noites especiais.",
    material: "Tecido premium com leve brilho acetinado. Composição mista para conforto e caimento perfeito.",
    care: "Lavar à mão com sabão neutro em água fria. Secar à sombra. Passar com ferro morno pelo avesso.",
    fit: "Modelagem ajustada que valoriza a silhueta. Comprimento midi. Segue tabela padrão de tamanhos."
  }
];

